department_catalog_url: https://trinity.duke.edu/departments
additional_course_catalog_urls:
  Arabic: https://asianmideast.duke.edu/courses/language/arabic
  Chinese: https://asianmideast.duke.edu/courses/language/chinese
  Hebrew: https://asianmideast.duke.edu/courses/language/hebrew
  Hindi: https://asianmideast.duke.edu/courses/language/hindi
  Japanese: https://asianmideast.duke.edu/courses/language/japanese
  Korean: https://asianmideast.duke.edu/courses/language/korean
  Persian: https://asianmideast.duke.edu/courses/language/persian
  Turkish: https://asianmideast.duke.edu/courses/language/turkish
  Urdu: https://asianmideast.duke.edu/courses/language/urdu
  Information Science + Studies: https://iss.duke.edu/courses
  Jewish Studies: https://jewishstudies.duke.edu/courses
  Latino/a Studies in the Global South: https://latinostudies.duke.edu/courses
skip_first_table_departments:
  - African & African American Studies
curriculum_codes:
  areas_of_knowledge:
    - ALP
    - CZ
    - NS
    - QS
    - SS
  modes_of_inquiry:
    - CCI
    - EI
    - FL
    - R
    - STS
    - W
  distribution_categories:
    - CE
    - HI
    - IJ
    - NW
    - QC
    - SB
course_descriptions_scraper_batch_size: 1000
sleep_time_sec: 2
curriculum_api_data_downloader_batch_size: 1000
